#from artifacts.developer.gov.bc.ca/docker-remote/fluent/fluent-bit:1.5.7
from fluent/fluent-bit:1.5.7

COPY fluent-bit.conf /fluent-bit/etc/
COPY parsers.conf /fluent-bit/etc/

CMD ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf", "-vv"]
