name: FluentBit - Build and push to Tools Emerald

on:
  workflow_dispatch:
  
env:
  INITIAL_TAG: latest
  TAG: dev
  NAME: fluentbit-splunk
  CONTEXT: docker/fluentbit/

jobs:
  build-fluentbit-splunk:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login
        run: |
          docker login -u ${{ secrets.EMERALD_CLUSTER_REGISTRY_USER }} -p ${{ secrets.EMERALD_BUILD_TOKEN }} ${{ secrets.EMERALD_CLUSTER_REGISTRY }}
      - name: Build n Tag
        run: |
          docker build -t ${{ env.NAME }}:${{ env.INITIAL_TAG }} ${{ env.CONTEXT }} -f ${{ env.CONTEXT }}Dockerfile.ci
          docker tag ${{ env.NAME }}:${{ env.INITIAL_TAG }} ${{ secrets.EMERALD_CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS_EMERALD }}/${{ env.NAME }}:${{ env.INITIAL_TAG }}
          docker tag ${{ env.NAME }}:${{ env.INITIAL_TAG }} ${{ secrets.EMERALD_CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS_EMERALD }}/${{ env.NAME }}:${{ env.TAG }}
      - name: Push
        run: |
          docker push --all-tags ${{ secrets.EMERALD_CLUSTER_REGISTRY }}/${{ secrets.NS_TOOLS_EMERALD }}/${{ env.NAME }}
