name: Deploy Fluentbit Splunk Image to GHCR

env:
    NAME: fluentbit-splunk
    GHCR_NAMESPACE: bcgov/jag-isb-monitoring-automation-tools
    CONTEXT: docker/fluentbit/
    INITIAL_TAG: latest
    # TODO: Implement per-env tags
    # TAG: dev


on:
  workflow_dispatch:
  push:
    branches:
      - main #TODO: Make for develop, test, and prod
    paths:
        - .github/workflows/fluentbit-splunk-ghcr.yml
        - docker/fluentbit/**

jobs:
      push-fluentbit-splunk-image:
        runs-on: ubuntu-latest
        # defaults:
        #   run:
        #     working-directory: './docker/fluentbit/'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build -t ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ env.NAME }}:latest ${{ env.CONTEXT }} -f ${{ env.CONTEXT }}Dockerfile.ci 
              docker push ghcr.io/${{ env.GHCR_NAMESPACE }}/${{ env.NAME }}:latest
